
## 数据源的配置s
spring:
  datasource:
    druid:
      username: root
      password: 123456
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/cloud_hospital?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true

## springboot 和 mybatis整合的配置
mybatis:
  type-aliases-package: com.dzqc.cloud.entity
  mapper-locations: classpath:mappers/*Mapper.xml
server:
  port: 80

## 现实日志
logging:
  level:
    com.dzqc.cloud.dao: debug #日志级别

## 阿里短信验证
alisms:
  accessKeyId: LTAI4G8Zfr1dq9KDFfVhTLYk
  accessSecret: X5ae2c1rpCUdq0r0lQUdYLZXY1l4Lt
  signName: Jklive
  templateCode: SMS_188626044

## 分页插件
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql